
run_type = "staged_learning"
device = "cpu"

[parameters]
prior_file = "../../reinvent4/priors/reinvent.prior"
agent_file = "C:\Users\user\Desktop\GP\backend\priors\prior_20250626_004009_ed92bfe2ab1a4e979f13d2eb7e014bc5.prior"
summary_csv_prefix = "my_curriculum_run"
batch_size = 64
randomize_smiles = true
unique_sequences = true

[learning_strategy]
type = "dap"
sigma = 128
rate = 0.0001

[diversity_filter]
type = "IdenticalMurckoScaffold"
bucket_size = 25
minscore = 0.4

[[stage]]
chkpt_file = "stage1.chkpt"
termination = "simple"
max_score = 0.6
min_steps = 25
max_steps = 100

[stage.scoring]
type = "geometric_mean"

[[stage.scoring.component]]
[stage.scoring.component.custom_alerts.endpoint]
name = "Unwanted SMARTS"
weight = 0.79
params.smarts = ['[*;r8]', '[#8][#8]', 'C#C']

[[stage.scoring.component]]
[stage.scoring.component.MolecularWeight.endpoint]
name = "Molecular weight"
weight = 0.342

[stage.scoring.component.MolecularWeight.transform]
type = double_sigmoid
low = 200.0
high = 500.0
coef_div = 500.0
coef_si = 20.0
coef_se = 20.0
