run_type = "staged_learning"
device = "cpu"
[[stage]]
chkpt_file = "agents\\agent_41bf113a0bd841d5b302f4471b8826e6.prior"
termination = "simple"
max_score = 0.6
min_steps = 5
max_steps = 5

[stage.scoring]
type = "geometric_mean"
[[stage.scoring.component]]

[stage.scoring.component.MolecularWeight]
comment = "Drug-like MW range"
[[stage.scoring.component.MolecularWeight.endpoint]]
name = "Molecular weight"
weight = 0.34

[stage.scoring.component.MolecularWeight.endpoint.transform]
type = "double_sigmoid"
low = 200.0
high = 500.0
coef_div = 500.0
coef_si = 20.0
coef_se = 20.0

[parameters]
summary_csv_prefix = "staged_learning_b3f7be6c2b7d49e4ab23c137ac744307"
batch_size = 64
randomize_smiles = true
unique_sequences = true
prior_file = "backend/priors/reinvent.prior"
agent_file = "agents\\agent_540863011bb84d32b191aa9805da482a.prior"

[learning_strategy]
type = "dap"
sigma = 128
rate = 0.0001

[diversity_filter]
type = "IdenticalMurckoScaffold"
bucket_size = 25
minscore = 0.4
